// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todo.proto

package todopb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TodoByIDRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TodoByIDRequest) Reset()         { *m = TodoByIDRequest{} }
func (m *TodoByIDRequest) String() string { return proto.CompactTextString(m) }
func (*TodoByIDRequest) ProtoMessage()    {}
func (*TodoByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{0}
}

func (m *TodoByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodoByIDRequest.Unmarshal(m, b)
}
func (m *TodoByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodoByIDRequest.Marshal(b, m, deterministic)
}
func (m *TodoByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodoByIDRequest.Merge(m, src)
}
func (m *TodoByIDRequest) XXX_Size() int {
	return xxx_messageInfo_TodoByIDRequest.Size(m)
}
func (m *TodoByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TodoByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TodoByIDRequest proto.InternalMessageInfo

func (m *TodoByIDRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type TodoByIDResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Completed            bool     `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TodoByIDResponse) Reset()         { *m = TodoByIDResponse{} }
func (m *TodoByIDResponse) String() string { return proto.CompactTextString(m) }
func (*TodoByIDResponse) ProtoMessage()    {}
func (*TodoByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{1}
}

func (m *TodoByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodoByIDResponse.Unmarshal(m, b)
}
func (m *TodoByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodoByIDResponse.Marshal(b, m, deterministic)
}
func (m *TodoByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodoByIDResponse.Merge(m, src)
}
func (m *TodoByIDResponse) XXX_Size() int {
	return xxx_messageInfo_TodoByIDResponse.Size(m)
}
func (m *TodoByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TodoByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TodoByIDResponse proto.InternalMessageInfo

func (m *TodoByIDResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TodoByIDResponse) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *TodoByIDResponse) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

type UploadImageRequest struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadImageRequest) Reset()         { *m = UploadImageRequest{} }
func (m *UploadImageRequest) String() string { return proto.CompactTextString(m) }
func (*UploadImageRequest) ProtoMessage()    {}
func (*UploadImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{2}
}

func (m *UploadImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadImageRequest.Unmarshal(m, b)
}
func (m *UploadImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadImageRequest.Marshal(b, m, deterministic)
}
func (m *UploadImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadImageRequest.Merge(m, src)
}
func (m *UploadImageRequest) XXX_Size() int {
	return xxx_messageInfo_UploadImageRequest.Size(m)
}
func (m *UploadImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadImageRequest proto.InternalMessageInfo

func (m *UploadImageRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type UploadImageResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadImageResponse) Reset()         { *m = UploadImageResponse{} }
func (m *UploadImageResponse) String() string { return proto.CompactTextString(m) }
func (*UploadImageResponse) ProtoMessage()    {}
func (*UploadImageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{3}
}

func (m *UploadImageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadImageResponse.Unmarshal(m, b)
}
func (m *UploadImageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadImageResponse.Marshal(b, m, deterministic)
}
func (m *UploadImageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadImageResponse.Merge(m, src)
}
func (m *UploadImageResponse) XXX_Size() int {
	return xxx_messageInfo_UploadImageResponse.Size(m)
}
func (m *UploadImageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadImageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadImageResponse proto.InternalMessageInfo

type DownloadImageRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadImageRequest) Reset()         { *m = DownloadImageRequest{} }
func (m *DownloadImageRequest) String() string { return proto.CompactTextString(m) }
func (*DownloadImageRequest) ProtoMessage()    {}
func (*DownloadImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{4}
}

func (m *DownloadImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadImageRequest.Unmarshal(m, b)
}
func (m *DownloadImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadImageRequest.Marshal(b, m, deterministic)
}
func (m *DownloadImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadImageRequest.Merge(m, src)
}
func (m *DownloadImageRequest) XXX_Size() int {
	return xxx_messageInfo_DownloadImageRequest.Size(m)
}
func (m *DownloadImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadImageRequest proto.InternalMessageInfo

type DownloadImageResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadImageResponse) Reset()         { *m = DownloadImageResponse{} }
func (m *DownloadImageResponse) String() string { return proto.CompactTextString(m) }
func (*DownloadImageResponse) ProtoMessage()    {}
func (*DownloadImageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{5}
}

func (m *DownloadImageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadImageResponse.Unmarshal(m, b)
}
func (m *DownloadImageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadImageResponse.Marshal(b, m, deterministic)
}
func (m *DownloadImageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadImageResponse.Merge(m, src)
}
func (m *DownloadImageResponse) XXX_Size() int {
	return xxx_messageInfo_DownloadImageResponse.Size(m)
}
func (m *DownloadImageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadImageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadImageResponse proto.InternalMessageInfo

func (m *DownloadImageResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*TodoByIDRequest)(nil), "todopb.TodoByIDRequest")
	proto.RegisterType((*TodoByIDResponse)(nil), "todopb.TodoByIDResponse")
	proto.RegisterType((*UploadImageRequest)(nil), "todopb.UploadImageRequest")
	proto.RegisterType((*UploadImageResponse)(nil), "todopb.UploadImageResponse")
	proto.RegisterType((*DownloadImageRequest)(nil), "todopb.DownloadImageRequest")
	proto.RegisterType((*DownloadImageResponse)(nil), "todopb.DownloadImageResponse")
}

func init() { proto.RegisterFile("todo.proto", fileDescriptor_0e4b95d0c4e09639) }

var fileDescriptor_0e4b95d0c4e09639 = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xdd, 0x4a, 0xfb, 0x40,
	0x10, 0xc5, 0xff, 0x9b, 0x7f, 0x2d, 0x76, 0xaa, 0xb5, 0x8c, 0x56, 0x43, 0xac, 0x50, 0xf7, 0x2a,
	0x20, 0x34, 0x7e, 0xbc, 0x81, 0x14, 0xa4, 0x5e, 0x49, 0xa8, 0xe0, 0xed, 0xd6, 0x5d, 0x42, 0x20,
	0xcd, 0xac, 0x66, 0xfd, 0x42, 0xbc, 0xf1, 0x15, 0x7c, 0x34, 0x5f, 0xc1, 0xe7, 0x10, 0x49, 0xd2,
	0xa5, 0x36, 0x8d, 0x77, 0xc3, 0xcc, 0xc9, 0x2f, 0xe7, 0x1c, 0x16, 0xc0, 0x90, 0xa4, 0xa1, 0xbe,
	0x27, 0x43, 0xd8, 0xcc, 0x67, 0x3d, 0xf5, 0xfa, 0x11, 0x51, 0x94, 0xa8, 0x40, 0xe8, 0x38, 0x10,
	0x69, 0x4a, 0x46, 0x98, 0x98, 0xd2, 0xac, 0x54, 0xf1, 0x43, 0xd8, 0x9a, 0x90, 0xa4, 0xf3, 0x97,
	0xf1, 0x28, 0x54, 0x77, 0x0f, 0x2a, 0x33, 0xd8, 0x01, 0x27, 0x96, 0x2e, 0x1b, 0x30, 0x7f, 0x2d,
	0x74, 0x62, 0xc9, 0x27, 0xd0, 0x5d, 0x48, 0x32, 0x4d, 0x69, 0xa6, 0xaa, 0x1a, 0x44, 0x68, 0x18,
	0xf5, 0x6c, 0x5c, 0x67, 0xc0, 0xfc, 0x56, 0x58, 0xcc, 0xd8, 0x87, 0xd6, 0x2d, 0xcd, 0x74, 0xa2,
	0x8c, 0x92, 0xee, 0xff, 0x01, 0xf3, 0xd7, 0xc3, 0xc5, 0x82, 0xfb, 0x80, 0xd7, 0x3a, 0x21, 0x21,
	0xc7, 0x33, 0x11, 0x29, 0xfb, 0x6f, 0x84, 0x86, 0x14, 0x46, 0x14, 0xe4, 0x8d, 0xb0, 0x98, 0x79,
	0x0f, 0xb6, 0x97, 0x94, 0xa5, 0x05, 0xbe, 0x0b, 0x3b, 0x23, 0x7a, 0x4a, 0xab, 0x08, 0x7e, 0x04,
	0xbd, 0xca, 0x7e, 0xee, 0xb9, 0x86, 0x7d, 0xfa, 0xcd, 0xa0, 0x91, 0x87, 0xc3, 0x1b, 0x68, 0x5f,
	0x28, 0x63, 0x73, 0xe2, 0xde, 0xb0, 0x6c, 0x6f, 0x58, 0x29, 0xc7, 0x73, 0x57, 0x0f, 0xd6, 0xcf,
	0xfb, 0xe7, 0xd7, 0x87, 0xd3, 0xc5, 0x4e, 0xf0, 0x78, 0x12, 0xe4, 0xa2, 0x2c, 0x78, 0x8d, 0xe5,
	0x1b, 0x5e, 0x42, 0xfb, 0x97, 0x7d, 0xf4, 0x2c, 0x60, 0x35, 0xbd, 0xb7, 0x5f, 0x7b, 0x9b, 0xf3,
	0xff, 0xf9, 0x0c, 0xaf, 0x60, 0x73, 0x29, 0x1b, 0xf6, 0xed, 0x17, 0x75, 0x55, 0x78, 0x07, 0x7f,
	0x5c, 0x2d, 0xf1, 0x98, 0x4d, 0x9b, 0xc5, 0x33, 0x38, 0xfb, 0x09, 0x00, 0x00, 0xff, 0xff, 0xfe,
	0x6a, 0x23, 0x68, 0x3a, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TodoClient is the client API for Todo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TodoClient interface {
	GetTodoByID(ctx context.Context, in *TodoByIDRequest, opts ...grpc.CallOption) (*TodoByIDResponse, error)
	UploadImage(ctx context.Context, opts ...grpc.CallOption) (Todo_UploadImageClient, error)
	DownloadImage(ctx context.Context, in *DownloadImageRequest, opts ...grpc.CallOption) (Todo_DownloadImageClient, error)
}

type todoClient struct {
	cc *grpc.ClientConn
}

func NewTodoClient(cc *grpc.ClientConn) TodoClient {
	return &todoClient{cc}
}

func (c *todoClient) GetTodoByID(ctx context.Context, in *TodoByIDRequest, opts ...grpc.CallOption) (*TodoByIDResponse, error) {
	out := new(TodoByIDResponse)
	err := c.cc.Invoke(ctx, "/todopb.Todo/GetTodoByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) UploadImage(ctx context.Context, opts ...grpc.CallOption) (Todo_UploadImageClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Todo_serviceDesc.Streams[0], "/todopb.Todo/UploadImage", opts...)
	if err != nil {
		return nil, err
	}
	x := &todoUploadImageClient{stream}
	return x, nil
}

type Todo_UploadImageClient interface {
	Send(*UploadImageRequest) error
	CloseAndRecv() (*UploadImageResponse, error)
	grpc.ClientStream
}

type todoUploadImageClient struct {
	grpc.ClientStream
}

func (x *todoUploadImageClient) Send(m *UploadImageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *todoUploadImageClient) CloseAndRecv() (*UploadImageResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadImageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *todoClient) DownloadImage(ctx context.Context, in *DownloadImageRequest, opts ...grpc.CallOption) (Todo_DownloadImageClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Todo_serviceDesc.Streams[1], "/todopb.Todo/DownloadImage", opts...)
	if err != nil {
		return nil, err
	}
	x := &todoDownloadImageClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Todo_DownloadImageClient interface {
	Recv() (*DownloadImageResponse, error)
	grpc.ClientStream
}

type todoDownloadImageClient struct {
	grpc.ClientStream
}

func (x *todoDownloadImageClient) Recv() (*DownloadImageResponse, error) {
	m := new(DownloadImageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TodoServer is the server API for Todo service.
type TodoServer interface {
	GetTodoByID(context.Context, *TodoByIDRequest) (*TodoByIDResponse, error)
	UploadImage(Todo_UploadImageServer) error
	DownloadImage(*DownloadImageRequest, Todo_DownloadImageServer) error
}

// UnimplementedTodoServer can be embedded to have forward compatible implementations.
type UnimplementedTodoServer struct {
}

func (*UnimplementedTodoServer) GetTodoByID(ctx context.Context, req *TodoByIDRequest) (*TodoByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTodoByID not implemented")
}
func (*UnimplementedTodoServer) UploadImage(srv Todo_UploadImageServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadImage not implemented")
}
func (*UnimplementedTodoServer) DownloadImage(req *DownloadImageRequest, srv Todo_DownloadImageServer) error {
	return status.Errorf(codes.Unimplemented, "method DownloadImage not implemented")
}

func RegisterTodoServer(s *grpc.Server, srv TodoServer) {
	s.RegisterService(&_Todo_serviceDesc, srv)
}

func _Todo_GetTodoByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TodoByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).GetTodoByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todopb.Todo/GetTodoByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).GetTodoByID(ctx, req.(*TodoByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_UploadImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TodoServer).UploadImage(&todoUploadImageServer{stream})
}

type Todo_UploadImageServer interface {
	SendAndClose(*UploadImageResponse) error
	Recv() (*UploadImageRequest, error)
	grpc.ServerStream
}

type todoUploadImageServer struct {
	grpc.ServerStream
}

func (x *todoUploadImageServer) SendAndClose(m *UploadImageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *todoUploadImageServer) Recv() (*UploadImageRequest, error) {
	m := new(UploadImageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Todo_DownloadImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadImageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TodoServer).DownloadImage(m, &todoDownloadImageServer{stream})
}

type Todo_DownloadImageServer interface {
	Send(*DownloadImageResponse) error
	grpc.ServerStream
}

type todoDownloadImageServer struct {
	grpc.ServerStream
}

func (x *todoDownloadImageServer) Send(m *DownloadImageResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Todo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "todopb.Todo",
	HandlerType: (*TodoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTodoByID",
			Handler:    _Todo_GetTodoByID_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadImage",
			Handler:       _Todo_UploadImage_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadImage",
			Handler:       _Todo_DownloadImage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "todo.proto",
}
